services:


  postgres:
    image: postgres:15
    ports:
      - "6543:5432"
    environment:
      POSTGRES_PASSWORD: 12345678

  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      DB_URL: jdbc:postgresql://postgres:5432/postgres